command_timeout = 10000
add_newline = true

[character]
success_symbol = '[➤](bold green)'
error_symbol = '[✗](bold red) '

[package]
disabled = true

[localip]
ssh_only = true
format = '[$localipv4](bold green) '
disabled = false
