# tealdeer (tldr) config

[updates]
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = false
download_languages = ["zh", "en"]

[search]
languages = ["zh", "en"]
