command_timeout = 10000

# 在提示符之间插入空行
add_newline = true

# 字符
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red) '

# 禁用 package 组件
[package]
disabled = true

[localip]
ssh_only = true
format = '[$localipv4](bold green) '
disabled = false
